### ISSUE TITLE
Unable to install API key

### ISSUE THREAD

**Issue by smach** [jcizel/FredR#1]
I am working in RStudio on Windows. I have a St. Louis Fed API key and stored it in a variable called api.key. However, when I try to run fred <- FredR(api.key) I receive this error message:

Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file './inst/data/categories.RData', probable reason 'No such file or directory'

Any ideas? I have been able to install an API key with the acs package api.key.install function.

Thanks.

**Comment by jcizel** [comment]
Hi, thanks for noticing the bug. I've corrected the code, so you should now be able to load the package without problems (it works on my Windows machine). Please, let me know if it works for you.

**Comment by smach** [comment]
All working fine now, thanks!

One more quick comment on your README file -- install instruction should be devtools::install_github("jcizel/FredR") and not devtools::install_github(jcizel/FredR)
